posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # ex: /posts/5/
    url(r'^full/(?P<article_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^comment/(?P<article_id>[0-9]+)/$', views.comment, name='comment'),
    # api
    url(r'^api/posts', views.all, name='api_all'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'website.views.home'),

    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

posts/models.py
import datetime
from django.db import models
from django.utils import timezone


# Create your models here.
# from posts.models import Article, Comment
# from django.utils import timezone
# a = Article(article_text="Lorem ipsum, whatever and dolor sid amet.", pub_date=timezone.now())
# a.save()
# a.id
# a.article_text
# Article.objects.all()
class Article(models.Model):
    article_title = models.CharField(max_length=100)
    article_text = models.TextField(max_length=1000)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __unicode__(self):
        return self.article_title


class Comment(models.Model):
    article = models.ForeignKey(Article)
    text = models.CharField(max_length=140)

    def __unicode__(self):
        return self.text

posts/views.py
from django.shortcuts import get_object_or_404, get_list_or_404
from django.shortcuts import render, redirect
from .models import Article, Comment
from django.http import JsonResponse
# from django.http import HttpResponse
# import json
# from django.utils.html import mark_safe
from django.core import serializers


# Create your views here.
def index(request):
    article_list = get_list_or_404(Article.objects.order_by('-pub_date')[:5])
    context = {'article_list': article_list}
    return render(request, 'posts/index.html', context)


def detail(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    comments = Comment.objects.filter(article_id=article_id)
    context = {'article': article, 'comments': comments}
    return render(request, 'posts/detail.html', context)


def comment(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    Comment.objects.create(
        article=article, text=request.POST['comment_text']
    )
    return redirect('posts:detail', article_id=article_id)


# API
def all(request):
    article_list = Article.objects.all().order_by('-pub_date')[0]
    data = serializers.serialize("json", article_list)
    return JsonResponse({'article_list': data})

    # json_posts = mark_safe(json.dumps(list(article_list), ensure_ascii=False))

    # return HttpResponse(
    #     json_posts,
    #     content_type="application/json"
    # )

website/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    return render(request, 'index.html')

posts/templates/posts/detail.html
<a href="{% url 'posts:index' %}">Home</a>
<h1>{{ article.article_title }}</h1>
<div>{{ article.pub_date }}</div>
{{ article.article_text}}
<hr>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'posts:comment' article.id %}" method="post">
{% csrf_token %}
<input type="text" name="comment_text">
<input type="submit" value="Comment" />
</form>

<ul>
{% for comment in comments %}
    <li>{{ comment.text }}</li>
{% endfor %}
</ul>

posts/templates/posts/index.html
{% if article_list %}
    <ul>
    {% for article in article_list %}
        <li><a href="{% url 'posts:detail' article.id %}">{{ article.article_title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No articles are available.</p>
{% endif %}

website/templates/index.html
<!doctype html>
<html>
<head>
    {% load staticfiles %}
    
  <!-- META -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"><!-- Optimize mobile viewport -->

  <title>This is a website</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <!-- Load styling -->
  <link rel="stylesheet" href="{% static 'style.css' %}">

  <script src="{% static 'vendor.js' %}"></script>
  <script src="{% static 'app.js' %}"></script>
  <script src="{% static 'templates.js' %}"></script>

</head>
<body ng-app="webz">
{% verbatim %}
<div ui-view></div>
{% endverbatim %}
</body>
</html>